(global-set-key (kbd "<f7> +")    'bookmark-set)
(global-set-key (kbd "<f7> -")    'bookmark-delete)
(global-set-key (kbd "<f7> ^")    'bookmark-jump)
(global-set-key (kbd "<f7> *")    'bookmark-bmenu-list)
(global-set-key (kbd "<f7> <f7>") 'bookmark-bmenu-list)
