;;; ThinkingBicycle.com stuff.

(setq thinking-bicycle-url "https://thinkingbicycle.com")
(defun thinking-bicycle ()
  (interactive)
  (browse-url thinking-bicycle-url))
(defun thinking-bicycle-bookmarks ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/users/bookmarks")))
(defun thinking-bicycle-folders ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/users/folders")))
(defun thinking-bicycle-recent-notes ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/users/recent_notes")))
(defun thinking-bicycle-read-laters ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/users/read_laters")))
(defun thinking-bicycle-received-shares ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/users/received_shares")))
(defun thinking-bicycle-my-posts ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/users/posts")))
(defun thinking-bicycle-my-posts-replies ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/users/posts_replies")))
(defun thinking-bicycle-search ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/keywords/search")))
(defun thinking-bicycle-advanced-search ()
  (interactive)
  (browse-url (concat thinking-bicycle-url "/keywords/advanced_search")))
(defun thinking-bicycle-add-uri ()
  (interactive)
  (when (string= major-mode "w3m-mode")
    (w3m-browse-url (concat thinking-bicycle-url
                            "/links/bookmarklet"
                            "?version=4"
                            "&uri="   w3m-current-url
                            "&title=" w3m-current-title))))

(global-set-key (kbd "<f7> <f7>") 'thinking-bicycle)
(global-set-key (kbd "<f7> b")    'thinking-bicycle-bookmarks)
(global-set-key (kbd "<f7> f")    'thinking-bicycle-folders)
(global-set-key (kbd "<f7> f")    'thinking-bicycle-recent-notes)
(global-set-key (kbd "<f7> l")    'thinking-bicycle-read-laters)
(global-set-key (kbd "<f7> p")    'thinking-bicycle-my-posts)
(global-set-key (kbd "<f7> P")    'thinking-bicycle-my-posts-replies)
(global-set-key (kbd "<f7> s")    'thinking-bicycle-received-shares)
(global-set-key (kbd "<f7> S")    'thinking-bicycle-search)
(global-set-key (kbd "<f7> +")    'thinking-bicycle-add-uri)
